package com.orchard.backend.api

import dev.autumn.annotations.BoundaryChannel
import dev.autumn.annotations.HotPath
import dev.autumn.annotations.LongLived
import dev.autumn.annotations.Pipelined
import dev.autumn.channel.AutumnChannel
import dev.autumn.channel.BoundaryDevice
import dev.autumn.channel.DeviceState
import com.orchard.backend.ipc.HttpGateway

@Pipelined
interface DocumentIntent {
    var categoryId: Int  // Enum mapped to string (1=workflow, 2=project, etc)
    var projectId: Int   // Hash or int mapping of project string
    var titleHash: Long
    var contentHash: Long
    // In a real SoA, the variable-length string payload is either written to a separate byte pool 
    // or passed via a structured array offset.
    var payloadOffset: Int
    var payloadLength: Int
}

@JvmInline
value class DocumentIntentFlyweight(val index: Int) : DocumentIntent {
    override var categoryId: Int get() = 0; set(v) {}
    override var projectId: Int get() = 0; set(v) {}
    override var titleHash: Long get() = 0; set(v) {}
    override var contentHash: Long get() = 0; set(v) {}
    override var payloadOffset: Int get() = 0; set(v) {}
    override var payloadLength: Int get() = 0; set(v) {}
}

@LongLived
@BoundaryChannel(capacity = 512)
@HttpGateway(port = 8080)
val documentIngressDevice = object : BoundaryDevice<DocumentIntent, DocumentIntent> {
    override val controlPlane = AutumnChannel<DeviceState>(8)
    override val ingressPlane = AutumnChannel<DocumentIntent>(512)
    override val egressPlane = AutumnChannel<DocumentIntent>(512)
}

@HotPath
fun onDocumentIntent(intent: DocumentIntent) {
    // In this hardware-modeled loop, we process standard Document intents 
    // generated by the Compose UI chat.
    
    // In a full implementation, we bridge the hardware ring array (pointer/offset data)
    // to Java heap memory via JNI or JVM File IO to save the Markdown to the OS.
    println("Received Document Intent: Category=${intent.categoryId}, Project=${intent.projectId}")
}
